### ISSUE TITLE
org-formation init does not output master account tags

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/org-formation-cli#100]
When calling `org-formation init`, tags declared on the master account are not part of the generated output file. Expected is that the output does contain the tags in the following format:
```
Organization:
  MasterAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: Organization Formation Test Account
      AccountId: '123123123123'
      RootEmail: email@org.com
      Tags:
        budget-alarm-threshold: '100'
        account-owner-email: email@org.com
```
