### ISSUE TITLE
Support ORG::PrincipalOrgID pseudo parameter in template

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/org-formation-cli#101]
would be good to support `ORG::PrincipalOrgID` as pseudo parameter in template.
e.g:
```
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: !Sub 'arn:aws:s3:::${ConfigConformsBucket}/*'
          Condition:
            StringEquals:
              aws:PrincipalOrgID: !Ref ORG::PrincipalOrgID
```
