### ISSUE TITLE
Have copy-to-s3 type support ZipBeforePut

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/org-formation-cli#107]
would be good to be able to do the following:

``` yaml
CopyToS3:
  Type: copy-to-s3
  RemotePath: 's3://bucket-name/code.zip'
  LocalPath: ./path/to/source/dir
  OrganizationBinding:
    Account: !Ref MyAccount
    Region: eu-central-1

DeployLambda:
  Type: update-stacks
  StackName: 'my-lambda'
  Template: ./lambda.yml
  Parameters:
    Code: s3://bucket-name/code.zip
  OrganizationBinding:
    Account: !Ref MyAccount
    Region: eu-central-1
```

Need to find a solution for the RemotePath to change whenever the sourcecode changes. maybe something like !MD5Dir
