### ISSUE TITLE
Use org-formation functions within a cloudformation template

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/org-formation-cli#108]
It would be great to be able to use functions like `!ReadFile`, `!MD5` and `!JsonString` inside a CloudFormation template. 
It would only be possible to use these functions when deploying using org-formation though.

This would for things like:
``` yaml
  LambdaUsingReadFile:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: my-lambda
      Runtime: nodejs12.x
      Role: !GetAtt MyRole.Arn
      Handler: index.handler
      Code:
        ZipFile: !ReadFile './my-lambda.js'
```

``` yaml
  MyPermissionSetWithReadableInlinePolicy:  
    Type: AWS::SSO::PermissionSet
    Properties: 
      Name: my-ps
      InstanceArn: !Ref instanceArn
      ManagedPolicies: 
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      InlinePolicy: !JsonString [ !ReadFile './my-inline-policy.json' ] 
```

edit: took out the Org::PrincipalOrgId example as it really is two different things
