### ISSUE TITLE
Support !Include function

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/org-formation-cli#114]
a `!Include` function could be used for multiple scenarios, one would be global parameters (example below).
Contents from the included file needs to be processed in the context of any of the files it is included from.

tasks.yml

``` yaml
Parameters: !Include './global-parameters.yml'

PrimaryRegion:
  Type: update-stacks
  Template: ./bucket.yml
  StackName: !Sub '${resourcePrefix}-stack-name-primary-region'
  DefaultOrganizationBindingRegion: !Ref primaryRegion
  DefaultOrganizationBinding:
    IncludeMasterAccount: !Ref includeMasterAccount
```

global-parameters.yml

``` yaml
allRegions:
  Type: List<String>
  Default: 
    - 'eu-central-1'
    - 'eu-west-1'
    - 'us-east-11'

primaryRegion:
  Type: String
  Default: 'eu-central-1'

resourcePrefix:
  Type: String
  Default: my

includeMasterAccount:
  Type: Boolean
  Default: true
```

**Comment by OlafConijn** [comment]
additionally, the possibility to overwrite included values using a merge operator (`<<:`)

``` yaml
Parameters: 
  <<: !Include './global-parameters.yml'
  
  primaryRegion:
    Type: String
    Default: 'us-east-1'

PrimaryRegion:
  Type: update-stacks
  Template: ./bucket.yml
  StackName: !Sub '${resourcePrefix}-stack-name-primary-region'
  DefaultOrganizationBindingRegion: !Ref primaryRegion # overwritten
  DefaultOrganizationBinding:
    IncludeMasterAccount: !Ref includeMasterAccount
```
