### ISSUE TITLE
error when attempting to disable account password expiration

### ISSUE THREAD

**Issue by zaro0508** [org-formation/org-formation-cli#145]
I want to disable password expiration however I get an error when I removing MaxPasswordAge from OC::ORG::PasswordPolicy.  The doc says that `MaxPasswordAge` is optional, https://github.com/org-formation/org-formation-cli/blob/master/docs/organization-resources.md#passwordpolicy

steps to repro:
1.  run org-formation update with password policy
```
  PasswordPolicy:
    Type: OC::ORG::PasswordPolicy
    Properties:
      MaxPasswordAge: 30
      MinimumPasswordLength: 12
      RequireLowercaseCharacters: true
      RequireNumbers: true
      RequireSymbols: true
      RequireUppercaseCharacters: true
      PasswordReusePrevention: 5
      AllowUsersToChangePassword: true
```
2.  remove MaxPasswordAge
3.  run org-formation update again
```
➜  org-formation update org-formation/organization.yml --profile my-profile --verbose
ERROR: unable to load file org-formation/organization.yml.
reason: expected PasswordReusePrevention to be a number, found undefined (undefined).
```

Note - i can remove MinimumPasswordLength and update without error.
