### ISSUE TITLE
feature: support a template engine

### ISSUE THREAD

**Issue by zaro0508** [org-formation/org-formation-cli#156]
For many simple use cases where we want to dynamically generate cloudformation templates we prefer to generate them using a template engine (we use jinja[1]).  We can use  a full programming language to translate to CFN (i.e. CDK or trophosphere) however templating is enough to get the job done in most of our use cases.  It would be great if org-formation can integrate with a templating engine.  I think something like nunjucks[2] would work really well.  Here's a nice article comparing a few javascript templating engines: https://strongloop.com/strongblog/compare-javascript-templates-jade-mustache-dust/

here's an example:
I want to create one security group that contains multiple ingress ports.

securitygroup.yaml:
```
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: 'vpc-1234ABC'
      SecurityGroupIngress:
      {% for port in IngressPorts %}
        - CidrIp: "0.0.0.0/0"
          FromPort: {{ port }}
          ToPort: {{ port }}
          IpProtocol: tcp
      {% endfor %}
```

passed in parameter:
```
IngressPorts:
  - 22
  - 80
```

result:
```
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: 'vpc-1234ABC'
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
        - CidrIp: "0.0.0.0/0"
          FromPort: 80
          ToPort: 80
          IpProtocol: tcp
```

[1] https://jinja.palletsprojects.com/en/2.11.x/
[2] https://mozilla.github.io/nunjucks/

**Comment by OlafConijn** [comment]
i am trying to figure out how this would work....

... would this be an additional attribute of `update-stacks` task? 
something like `TemplateTransform: { Data: xs:any }`
or would this be an additional task type?

would certain data be available by default?

**Comment by eduardomourar** [comment]
I would be in favor of Jinja because the AWS Proton team already is using it: https://docs.aws.amazon.com/proton/latest/adminguide/svc-pipeline.html

Or even better use CDK when we have everything cloudformation natively: https://github.com/aws/aws-proton-public-roadmap/issues/21

**Comment by zaro0508** [comment]
@eduardomourar jinja would be great!  I only suggested nunjucks because it's javascript based.  Jinja is written in python so I just wasn't sure how well it can be integrated.

@OlafConijn i could see working as a new org-formation type (i.e. update-templatized-stack) with a special parameter (i.e  TemplatizedData) to allow passing in variables.   for example..

org-formation-tasks.yaml
```
AppSecurityGroup:
  Type: update-templatized-stack
  Template: ./securitygroup.yaml
  StackName: app-security-group
  TemplatizedData:
     IngressPorts:
       - 22
       - 80  
  MaxConcurrentStacks: 10
  DefaultOrganizationBinding:
    IncludeMasterAccount: true
    Account: '*'
    Region: us-east-1
```

securitygroup.yaml:
```
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: 'vpc-1234ABC'
      SecurityGroupIngress:
      {% for port in TemplatizedData.IngressPorts %}
        - CidrIp: "0.0.0.0/0"
          FromPort: {{ port }}
          ToPort: {{ port }}
          IpProtocol: tcp
      {% endfor %}
```
