### ISSUE TITLE
Allow cross-account stack update to run as a StackSet

### ISSUE THREAD

**Issue by eduardomourar** [org-formation/org-formation-cli#159]
To leverage using more native AWS services, it would be nice if during a stack update we could run in StackSet mode. Here would a possible task using a proposed `UseStackSet` boolean property:

```yaml
RoleStackSet:
  Type: update-stacks
  Template: ./role.yml
  StackName: role-stackset
  UseStackSet: true
  DefaultOrganizationBindingRegion: us-east-1
  DefaultOrganizationBinding:
    IncludeMasterAccount: true
    Account: '*'
  Parameters:
    roleName: 'admin'
```

Where the actual deployment would become this in the end:

```yaml
AWSTemplateFormatVersion: '2010-09-09-OC'

Parameters:
  roleName:
    Type: String

Resources:

  WrapperStackSet:
    Type: AWS::CloudFormation::StackSet
    OrganizationBinding:
      IncludeMasterAccount: true
    Properties:
      StackSetName: role-stackset
      PermissionModel: SELF_MANAGED
      AdministrationRoleARN: !Sub 'arn:aws:iam::${ManagementAccount}:role/${ManagementAccount.BuildAccessRoleName}'
      ExecutionRoleName: !GetAtt CurrentAccount.BuildAccessRoleName
      Capabilities:
        - CAPABILITY_NAMED_IAM
      Parameters:
        - ParameterKey: roleName
          ParameterValue: !Ref roleName
      TemplateBody: !ReadFile ./role.yml
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts: Fn::EnumTargetAccounts DefaultOrganizationBinding ${account}
          Regions: Fn::EnumTargetRegions DefaultOrganizationBinding ${region}
```
