### ISSUE TITLE
copy-to-s3: support s3:// and https:// source

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/org-formation-cli#175]
Would be great to have copy-to-s3 support a source-file hosted on s3 or over http.
Also rename LocalPath => Source and RemotePath => Destination (destination obviously must be s3).
- ZipBeforePuth would only work with a local directory
- Print a warning for use of LocalPath / RemotePath, but would be automatically assigned to Source/Destination

current:
``` yaml
OrganizationFormationInitialCommit:
  Type: copy-to-s3
  LocalPath: 'initial-commit.zip'
  RemotePath: !Sub 's3://organization-formation-deployments-${accountId}-prd/initial-commit.zip'
  OrganizationBinding:
    Account: !Ref accountId
    Region: !Ref primaryRegion
```

desired (source could still be 'initial-commit.zip' when referencing a local file):
``` yaml
OrganizationFormationInitialCommit:
  Type: copy-to-s3
  Source: https://usercontent.github.com/initial-commit.zip
  Destination: !Sub 's3://organization-formation-deployments-${accountId}-prd/initial-commit.zip'
  OrganizationBinding:
    Account: !Ref accountId
    Region: !Ref primaryRegion
```
