### ISSUE TITLE
copy-to-s3: support BeforeCopyCommand

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/org-formation-cli#176]
Would be great to specify a command that will be ran before copy-to-s3 executes.
Intended usecase would could be building a typescript project, even before, ZipBeforePut packages the directory.

Checking whether or not the task should be executed based on the contents of the file or directory should be done before executing the command. As the command is likely to modify the contents of the directory the user must be aware that running the copy-to-s3 task a second time without reverting the directory to its original state will cause the task to rerun....

``` yaml
DeployLambda:
  Type: copy-to-s3
  Source: ./src/ 
  BeforeCopyCommand: "npm ci && npm run build"
  ZipBeforePut: true
  Destination: !Sub 's3://bucket/lambda.zip' 
  OrganizationBinding:
    Account: !Ref accountId
    Region: !Ref primaryRegion
 ```
