### ISSUE TITLE
parser: support multiple '<<' merge operators within the same parent

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/org-formation-cli#177]
this should allow for big files to be split in multiple smalller, e.g:
``` yaml
StagingOU:
  Type: OC::ORG::OrganizationalUnit
  Properties:
    OrganizationalUnitName: Staging
    Accounts:
      - !Ref InfraStagingAccount
      - !Ref KaufberaterStagingAccount

<<: !Include "../bunch-of-accounts-1.yml"
<<: !Include "../bunch-of-accounts-2.yml"
<<: !Include "../bunch-of-accounts-3.yml"
```

see also: https://github.com/org-formation/org-formation-cli/discussions/172
