### ISSUE TITLE
Feat: Support creating a govcloud accounts using organization model.

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/org-formation-cli#186]
As part of supporting multiple partitions it would be useful if account creation would support automated creation of govcloud accounts.

The OrganizationRoot resource would be used to enable this feature using a boolean property:
``` yaml
  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultBuildAccessRoleName: OrganizationFormationBuildRole
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole
      MirrorInGovCloud: true # please help me out with naming :)
```
When MirrorInGovCloud is set to true:
- The OU structure (Accounts and OUs) on the commercial side will be mirrored on the gov side.
- Instead of using [CreateAccount](https://docs.aws.amazon.com/cli/latest/reference/organizations/create-account.html), 
- The AccountId attribute in the model will refer to the AccountId on the commercial side. The AccountId is optional (except for the Management Account). 
  - Maybe it is fair to kick this one down the road a little bit. Resolving !GetAtt MyAccount.AccountId will return the right AccountId based on the OrganizationBinding - which needs to be extended and this is a different story. [CreateGovCloudAccount](https://docs.aws.amazon.com/cli/latest/reference/organizations/create-gov-cloud-account.html) is used
- Defining Password Policies, IAM Alias, Support level and/or SCPs is not supported. It might just throw an error while loading. this is: 
  1. To simplify the first iteration of this feature 
  1. We are moving away from defining these in the organization.yml model in hopes that AWS Organizations will release CFN support some day 
  1. Having two organizations that are mirrored doesn't allow you to selectively apply these values to either one of the organizations. This can be done using organization bindings and therefore the advice would be to use update-stacks and private types to implement these concerns 
- you might (or might not?) be able to turn MirrorInGovCloud to false, but nothing magical will happen.

Implementation notes
TBD, after having agreement on the above
