### ISSUE TITLE
Pass in parameters depending on account binding

### ISSUE THREAD

**Issue by zaro0508** [org-formation/org-formation-cli#206]
### Subject of the issue
I would like to create a custom VPC in multiple member accounts with non-overlapping subnet prefixes. 

here’s an example.  i have two member accounts (memberX & memberY) in  my org and this is in my ofn config:
```
ScWorkbenchSwDeVpc:
  Type: update-stacks
  Template: https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/VPC/vpc-mini.yaml
  StackName: ScWorkbenchSwDeVpc
  Parameters:
    VpcSubnetPrefix: "10.201.30"
    VpcName: swdevvpc
  MaxConcurrentStacks: 10
  DefaultOrganizationBinding:
    IncludeMasterAccount: false
    Account: '*'
    Region: us-east-1
```

ofn creates the same VPC in both accounts with the same subnet prefix, `10.201.30`.  what I want is for ofn to create `10.201.30` in member account X and `10.201.31` in member account Y.

I guess I can create a duplicate ScWorkbenchSwDeVpc2 with `VpcSubnetPrefix: "10.201.31"` but that seems like needless duplication and it breaks the principal of DRY.

I would like to somehow apply a different set of parameter values to each account that ofn deploys to.

### Your environment
* version of org-foramtion (ofn --version)
0.9.15-beta.10
* version of node (node --version)
v15.5.1
* which OS/distro
macOS Mojave

**Comment by zaro0508** [comment]
@OlafConijn suggested a not-yet supported feature: 

```
Mappings:
  VcpSettings:
    VpcSubnetPrefix:
      111111111111: "10.201.30"
      222222222222: "10.201.31"

Parameters:
  VpcSubnetPrefix:  !FindInMap [VcpSettings, VpcSubnetPrefix, !Ref CurrentAccount]
```
