### ISSUE TITLE
[Bug] Adding a new policy arn does not update the stack

### ISSUE THREAD

**Issue by hffmnn** [org-formation/org-formation-cli#214]
### Subject of the issue

Changing the input of a task does not trigger an update on the stack

### Your environment

* version of org-foramtion 0.9.14
* version of node (node --version) v12.19.0
* Curren macOS 11.2.1

### Steps to reproduce

Give I have already deployed the following task:

```yaml
DeveloperRole:
  Type: update-stacks
  Template: ./templates/cross-account-role.yml
  StackName: my-developer-role
  StackDescription: Developer Role Example
  TerminationProtection: true
  Parameters:
    resourcePrefix: my
    roleName: developer-role
    rolePolicyArns:
      - arn:aws:iam::aws:policy/PowerUserAccess
  OrganizationBindings:
    AssumeRoleBinding:
      Account: !Ref MasterAccount
    RoleBinding:
      OrganizationalUnit: !Ref DevelopmentOU
  MaxConcurrentStacks: 10
  FailedStackTolerance: 10
```

where ` ./templates/cross-account-role.yml` is from the [examples folder](https://github.com/org-formation/org-formation-cli/blob/master/examples/templates/cross-account-role.yml). When adding one more policy to the `roloPolicyArns` (e.g. `arn:aws:iam::aws:policy/AdministratorAccess`) and runnig `org-formation perform-tasks tasks.yml` I get the following output

```
INFO: Executing: update-organization organization.yml.
INFO: organization up to date, no work to be done.
INFO: Task OrganizationUpdate execute successful.
INFO: Executing: update-stacks templates/cross-account-role.yml my-developer-role.
INFO: Stack my-developer-role already up to date.
INFO: Task DeveloperRole execute successful.
```

### Expected behaviour

An update should be triggered and the role should be updated.

### Actual behaviour

The role gets not updated and still only shows `arn:aws:iam::aws:policy/PowerUserAccess` as policy.

### Workaround

A possible workaround is to comment the `DeveloperRole`, run `org-formation perform-tasks tasks.yml   --perform-cleanup ` re-enalbe  `DeveloperRole` and run `org-formation perform-tasks tasks.yml` again.
