### ISSUE TITLE
print-tasks fails when using `!Ref CurrentAccount`

### ISSUE THREAD

**Issue by zaro0508** [org-formation/org-formation-cli#221]
### Subject of the issue
Running `ofn print-tasks` fails when running with ofn templates that contain a `!Ref CurrentAccount` and the error message provided isn't real clear on why it failed.

### Your environment
* ofn 0.9.15-beta.12
* node v15.5.1
* MAC Mojave 10.14.6

### Steps to reproduce
create following _task.yaml:
```
Mappings:
  VcpSettings:
    VpcSubnetPrefix:
      1111111111111: "10.201.30"
      2222222222: "10.201.31"

ScWorkbenchSwDeVpc:
  Type: update-stacks
  Template: https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/VPC/vpc-mini.yaml
  StackName: ScWorkbenchSwDeVpc
  Parameters:
    VpcSubnetPrefix:  !FindInMap [VcpSettings, VpcSubnetPrefix, !Ref CurrentAccount]
    VpcName: swdevvpc
  MaxConcurrentStacks: 10
  DefaultOrganizationBinding:
    IncludeMasterAccount: false
    Account: [!Ref MemberXAccount, !Ref MemberYAccount]
    Region: us-east-1
```

run print-tasks..
```
ofn print-tasks _tasks.yaml --profile myprofile --output yaml --max-concurrent-stacks 100 --max-concurrent-tasks 100 --verbose
```

### Expected behaviour
print should not fail because the yaml is valid and it works with peform-tasks command.  if it makes sense to fail then it should provide a better error message

### Actual behaviour
get error.. `print failed. reason: Unable to perform FindInMap as there is no mappings section` which doesn't seem like a good enough error for users to figure out the problem.

<details>
  <summary>print-tasks log</summary>

			➜  npx org-formation print-tasks _tasks.yaml --profile testitorgmgnt-CiServiceRole --output yaml --max-concurrent-stacks 100 --max-concurrent-tasks 100 --verbose
			WARN: Task PasswordPolicy depends on task CommunityIamPasswordPolicyRP which was not found.
			WARN: Task Ec2EbsEncryptionDefaults depends on task CommunityEc2EbsEncryptionDefaultsRP which was not found.
			WARN: Task Ec2NoVpcDefaults depends on task CommunityEc2NoDefaultVpcRP which was not found.
			WARN: Task AccessTestItOrgMgntAdmin depends on task CommunityIamSamlProviderRP which was not found.
			DEBG: Task OrganizationUpdate print starting...
			INFO: Executing: update-organization organization.yaml.
			DEBG: Task Types print starting...
			DEBG: Task SeviceControlPolicies print starting...
			DEBG: Task PreventDisableGuardDuty print starting...
			DEBG: Task Baseline print starting...
			DEBG: Task PasswordPolicy print starting...
			DEBG: Task AccountDefaults print starting...
			DEBG: Task Ec2EbsEncryptionDefaults print starting...
			DEBG: Task AccountAccess print starting...
			DEBG: Task AccessTestItOrgMgntAdmin print starting...
			DEBG: Done performing task(s).
			INFO: Task Types print successful.
			INFO: organization up to date, no work to be done.
			INFO: Task OrganizationUpdate print successful.
			INFO: Task PasswordPolicy print successful.
			DEBG: Task OrgFormationBuildAccessRole print starting...
			INFO: Task PreventDisableGuardDuty print successful.
			DEBG: Task PreventDisableCloudtrail print starting...
			INFO: Task Ec2EbsEncryptionDefaults print successful.
			DEBG: Task Ec2NoVpcDefaults print starting...
			INFO: Task AccessTestItOrgMgntAdmin print successful.
			DEBG: Done performing task(s).
			INFO: Task AccountAccess print successful.
			INFO: Task Ec2NoVpcDefaults print successful.
			DEBG: Task SceptreCloudformationBucket print starting...
			INFO: Task PreventDisableCloudtrail print successful.
			DEBG: Task PreventDisableCloudwatchConfigs print starting...
			INFO: Task OrgFormationBuildAccessRole print successful.
			DEBG: Done performing task(s).
			INFO: Task Baseline print successful.
			INFO: Task PreventDisableCloudwatchConfigs print successful.
			DEBG: Task DenyAllRegionsOutsideUsEast1 print starting...
			INFO: Task SceptreCloudformationBucket print successful.
			DEBG: Task SceptreLambdaBucket print starting...
			INFO: Task SceptreLambdaBucket print successful.
			DEBG: Task ItKmsKey print starting...
			INFO: Task DenyAllRegionsOutsideUsEast1 print successful.
			DEBG: Task DenyAllRegionsOutsideUs print starting...
			INFO: Task ItKmsKey print successful.
			DEBG: Task ScWorkbenchKmsKey print starting...
			INFO: Task DenyAllRegionsOutsideUs print successful.
			DEBG: Done performing task(s).
			INFO: Task SeviceControlPolicies print successful.
			INFO: Task ScWorkbenchKmsKey print successful.
			DEBG: Task ScWorkbenchSwDeVpc print starting...
			ERROR: Task ScWorkbenchSwDeVpc print failed. reason: Unable to perform FindInMap as there is no mappings section found.
			ERROR:
			ERROR: ==========================
			ERROR: Stopped performing task(s)
			ERROR: Following tasks completed:
			ERROR:  - Task Ec2EbsEncryptionDefaults
			ERROR:  - Task Ec2NoVpcDefaults
			ERROR:  - Task SceptreCloudformationBucket
			ERROR:  - Task SceptreLambdaBucket
			ERROR:  - Task ItKmsKey
			ERROR:  - Task ScWorkbenchKmsKey
			ERROR: Following tasks failed:
			ERROR:  - Task ScWorkbenchSwDeVpc
			ERROR: ==========================
			ERROR:
			ERROR: Task AccountDefaults print failed. reason: Number of failed tasks 1 exceeded tolerance for failed tasks 0.
			WARN:
			WARN: ========================
			WARN: Done performing task(s): 1 failed but did not exceed tolerance for failed tasks 99
			WARN: Following tasks failed:
			WARN:  - Task AccountDefaults
			WARN: ========================
			WARN:

</details>
