### ISSUE TITLE
Service Control Policy. Condition in statement

### ISSUE THREAD

**Issue by dobeerman** [org-formation/org-formation-cli#225]
### Subject of the issue
In `organization.yml` I'm trying to create a SCP. If policy statement has `Condition` parameter, update process fails with the following exception:

```
ERROR: failed executing task: Update OC::ORG::ServiceControlPolicy DeveloperRoleSCP MalformedPolicyDocumentException: The provided policy document does not meet the requirements of the specified policy type.
ERROR: error: MalformedPolicyDocumentException, aws-request-id: 37994774-1153-4a69-aa67-20ddfb5f7f87
ERROR: The provided policy document does not meet the requirements of the specified policy type.
```

### Your environment
* version of org-foramtion **0.9.15-beta.11**
* version of node **v12.18.3**
* which OS/distro **Ubuntu 20.04.2 LTS**

### Steps to reproduce

Add the following SCP and update org-formation
```yaml
  DeveloperRoleSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: DeveloperRole
      Description: Deny access to unnecessary resources
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DeveloperRoleEC2
            Effect: Allow
            Action:
              - 'ec2:StopInstances'
              - 'ec2:StartInstances'
              - 'ec2:TerminateInstances'
              - 'ec2:RunInstances'
            Resource:
              - '*'
            Condition:
              StringLikeIfExists:
                'ec2:InstanceType':
                  - 't2.*'
```

You will get an exception like above.
If you remove the `Condition` parameter, update process will succeed.

But, if you create the same SCP with `Condition` parameter via AWS console and download a new `organization.yml`, all works fine until you change `Condition` parameter.

### Expected behaviour
Able to update `Condition` parameter.

### Actual behaviour
Unable to make a changes.
