### ISSUE TITLE
Support using `Fn::Sub`/`!Sub` and `Fn::Cmd`/`!Cmd` intrinsic functions together

### ISSUE THREAD

**Issue by mbarneyjr** [org-formation/org-formation-cli#242]
### Support using `Fn::Sub`/`!Sub` and `Fn::Cmd`/`!Cmd` intrinsic functions together

I'd like to be able to do something similar to the following:

```yml
SomeStringJson:
  Fn::Sub: !Cmd generate-json-cli
```

Where `generate-json-cli` returns json that expects to be passed to the `Fn::Sub`/`!Sub` intrinsic function, like this:

```json
{
  "some-property": "${resourcePrefix}-some-value"
}
```

### Your environment
* version of org-foramtion (ofn --version)
```bash
$ ofn --version
0.9.15
```
* version of node (node --version)
```bash
$ node --version
v14.15.4
```
* which OS/distro
OS X
```bash
$ uname -a
Darwin T10059.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
```

### Steps to reproduce
Create a CloudFormation template similar to the following:
```yml
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  resourcePrefix:
    Type: String
Resources:
  Parameter:
    Type: AWS::SSM::Parameter
    Name: some-name
    Value:
      Fn::Sub: !Cmd cat file.json
```
where you have a `file.json` with the following:
```json
{
  "some-property": "${resourcePrefix}-some-value"
}
```

### Expected behaviour
Running `print-tasks` should generate a template that looks similar to the following:
```json
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Parameters": {
        "resourcePrefix": {
            "Type": "String"
        }
    },
    "Resources": {
        "Parameter": {
            "Type": "AWS::SSM::Parameter",
            "Name": "some-name",
            "Value": {
                "Fn::Sub": "{\"some-property\":\"${resourcePrefix}-some-value\"}"
            }
        }
    }
}
```

### Actual behaviour
I get an error:
```bash
ERROR: Task DoThing print failed. reason: unable to parse !Sub expression
```

**Comment by zaro0508** [comment]
I believe you can accomplish this same use case by using the new ofn templating feature, https://github.com/org-formation/org-formation-cli/blob/master/docs/task-files.md#templating

**Comment by mbarneyjr** [comment]
Yeah that was my work around (may not be exact):

```yml
# task.yml
SomeTask:
  ...
  TemplatingContext:
    Value: !Cmd cat file.json
    
# template.yml
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  resourcePrefix:
    Type: String
Resources:
  Parameter:
    Type: AWS::SSM::Parameter
    Name: some-name
    Value: !Sub |
      {{ Value | indent('4') }}
```

But it'd be nice to have the `!Cmd` evaluated first so the validation of the template doesn't fail

The templating feature definitely came in handy! Really happy to have a workaround initially until this issue is resolved
