### ISSUE TITLE
Support CloudFormation Stack-level tags

### ISSUE THREAD

**Issue by mbarneyjr** [org-formation/org-formation-cli#261]
### Support tagging deployed CloudFormation stacks

In the `update-stacks` task, it'd be really convenient to support a `Tags` property, to apply [stack-level tags](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFormation.html#createStack-property) to CloudFormation stack deployments, which automatically get applied to (supported) resources. An example task file would be something like this:

```yml
Parameters: !Include ../organization-parameters.yml

GuardDuty:
  Type: update-stacks
  Template: ./templates/guardduty.yml
  StackName: !Sub ${OrganizationName}-guardduty
  Parameters:
    OrganizationName: !Ref OrganizationName
  Tags:
    - Key: OrganizationName
      Value: !Ref OrganizationName
  MaxConcurrentStacks: 32
  DefaultOrganizationBindingRegion: !Ref PrimaryRegion
  OrganizationBindings:
    GuardDutyMemberBinding:
      AccountsWithTag: guardduty-member
    GuardDutyMasterBinding:
      AccountsWithTag: guardduty-master
```

In which the CloudFormation stacks that get created from this task would contain the stack tags `OrganizationName: 'some-organization'`

**Comment by OlafConijn** [comment]
hi @mbarneyjr 

Just released a new beta that contains support for this: `npm i aws-organization-formation@0.9.17-beta.14`
The difference with your example is that tags are configured as a complex type (not array of Key/Value).

```
GuardDuty:
  Type: update-stacks
  Template: ./templates/guardduty.yml
  StackName: !Sub ${OrganizationName}-guardduty
  Parameters:
    OrganizationName: !Ref OrganizationName
  Tags:
    OrganizationName: !Ref OrganizationName
    SomethingElse: another tag
```
