### ISSUE TITLE
!GetAtt for CurrentAccount.Tags.<key> returns [object object]

### ISSUE THREAD

**Issue by LRuttenCN** [org-formation/org-formation-cli#265]
Hey! I like to work with org-formation. I just stumbled upon this quirk:

### Subject of the issue
When I use !GetAtt CurrentAccount.Tags.<tag key>, it gets translated to an [object object] string instead of the value.

### Your environment
* version of org-formation (v0.9.16)

### Steps to reproduce
In organization.yml:
```
  SharedSecurityAccount:
    Type: OC::ORG::Account
    Properties:
      ...other props here...
      Tags:
        EnvName: Test
```

In task file:
```
OrgParams:
  Type: update-cdk
  Path: ./
  CustomDeployCommand: !Sub npm ci && npm run build && npx cdk deploy --require-approval never${CurrentTask.Parameters} --all
  Parameters:
    EnvName: !GetAtt CurrentAcount.Tags
```

### Expected behaviour
I expect there to be a `-c EnvName=Test` when the command runs 

### Actual behaviour
Instead it runs with `-c EnvName=[object object]`.
