### ISSUE TITLE
Stacks are deleted one at a time even when there are no dependencies

### ISSUE THREAD

**Issue by craighurley** [org-formation/org-formation-cli#274]
### Subject of the issue
Stacks seem to be deleted one at a time.

### Your environment
* version of org-formation: 0.9.17
* version of node: 12.18
* which OS/distro: macos 11.5.2

### Steps to reproduce

`tasks.yaml`:
```
# ExtraTasks:
#   Type: include
#   Path: tasks-extra.yaml
#   MaxConcurrentTasks: 10
```

`tasks-extra.yaml`:
```
A:
  Type: update-stacks
  Template: ./templates/a.template
  MaxConcurrentStacks: 10
  ...

B:
  Type: update-stacks
  Template: ./templates/b.template
  MaxConcurrentStacks: 10
  ...
```

I commented out the ExtaTasks in `tasks.yaml` and ran `org-formation perform-tasks ./tasks.yaml --profile $AWS_PROFILE --perform-cleanup` so that the stacks in tasks-extra.yaml would be removed.

### Expected behaviour
Stacks get deleted in parallel if there are no dependencies. 

### Actual behaviour
Stacks get deleted one at a time, making `--perform-cleanup` very slow.
