### ISSUE TITLE
copy-to-s3 gets AccessDenied when S3 Bucket Encryption is enforced via SCP

### ISSUE THREAD

**Issue by jim-barber-he** [org-formation/org-formation-cli#287]
### Subject of the issue
I was trying to use a `copy-to-s3` task to copy a file to an S3 bucket and was failing with the following error:
```
INFO: Executing: include tasks/guard-duty/tasks.yml.
INFO: Executing: update-stacks tasks/guard-duty/trusted-ips-bucket.yml he-guardduty-trusted-ips-bucket.
INFO: Stack he-guardduty-trusted-ips-bucket already up to date.
INFO: Task GuardDutyTrustedIpsBucket execute successful.
INFO: Executing: copy-to-s3 GuardDutyTrustedIps.
ERROR: Workload GuardDutyTrustedIps in 358150449161/ap-southeast-2 updated failed. reason: Access Denied (358150449161 = SharedComplianceAccount)
Access Denied (use option --print-stack to print stack)
ERROR: 
ERROR: ==========================
ERROR: Stopped performing task(s)
ERROR: Following tasks failed: 
ERROR:  - Workload GuardDutyTrustedIps in 358150449161/ap-southeast-2 (358150449161 = SharedComplianceAccount)
ERROR: ==========================
ERROR: 
ERROR: Task GuardDutyTrustedIps execute failed. reason: Number of failed tasks 1 exceeded tolerance for failed tasks 0.
ERROR: 
ERROR: ==========================
ERROR: Stopped performing task(s)
ERROR: Following tasks completed: 
ERROR:  - Task GuardDutyTrustedIpsBucket
ERROR: Following tasks failed: 
ERROR:  - Task GuardDutyTrustedIps
```

It was determined that the cause was having this SCP set on the account:
```
  RequireEncryptiononAllAmazonS3BucketsSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: Require Encryption on All Amazon S3 Buckets
      Description: All objects added to S3 buckets must have AES256 server-side encryption.
      PolicyDocument:
        Statement:
          - Action:
              - s3:PutObject
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption': AES256
            Effect: Deny
            Resource: '*'
          - Action:
              - s3:PutObject
            Condition:
              Bool:
                's3:x-amz-server-side-encryption': false
            Effect: Deny
            Resource: '*'
        Version: 2012-10-17
```

Removing this SCP allowed the `copy-to-s3` step to pass.

### Your environment
* version of org-formation (ofn --version)
```
$ ofn --version
0.9.16
```
* version of node (node --version)
Out build pipeline uses the `orgformation/org-formation-cli:0.9.16` Docker image which has node version `v12.18.4`
I also ran it directly on my host which has node `v12.22.5`
* which OS/distro
On my host `Linux Debian 11 Bullseye`
The Docker image is `Alpine Linux v3.11.6`

### Steps to reproduce
Tell us how to reproduce this issue. Please provide ofn projct files if possible,
you can use [this template](https://plnkr.co/edit/m568SDw2KPufQsUl?p=preview) as a base.
https://plnkr.co/edit/m568SDw2KPufQsUl

I used the SCP as shown in the description.
I had tasks like so:
```
GuardDutyTrustedIpsBucket:
  DefaultOrganizationBinding:
    Account: !Ref SharedComplianceAccount
  DefaultOrganizationBindingRegion: !Ref primaryRegion
  Parameters:
    BucketName: he-guardduty-trusted-ips
  StackDescription: GuardDuty - Trusted IPs bucket
  StackName: he-guardduty-trusted-ips-bucket
  TerminationProtection: true
  Template: trusted-ips-bucket.yml
  Type: update-stacks

GuardDutyTrustedIps:
  DependsOn: GuardDutyTrustedIpsBucket
  LocalPath: ./trusted-ips.txt
  OrganizationBinding:
    Account: !Ref SharedComplianceAccount
    Region: !Ref primaryRegion
  RemotePath: s3://he-guardduty-trusted-ips/trusted-ips.txt
  Type: copy-to-s3
```

And the bucket created like so in the template:
```
  GuardDutyBucket:
    DeletionPolicy: Retain
    OrganizationBinding:
      Account: !Ref AccountId
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: he-guardduty-finding
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
```
and
```
  GuardDutyBucketPolicy:
    OrganizationBinding: !Ref LogArchiveBinding
    Properties:
      Bucket: !Ref GuardDutyBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetBucketLocation
              - s3:PutObject
            Effect: Allow
            Principal:
              Service: guardduty.amazonaws.com
            Resource:
              - !GetAtt GuardDutyBucket.Arn
              - !Sub arn:aws:s3:::${GuardDutyBucket}/*
        Version: 2012-10-17
    Type: AWS::S3::BucketPolicy
```

### Expected behaviour
Tell us what should happen
The `copy-to-s3` copies a file to the S3 bucket.

### Actual behaviour
Tell us what happens instead
It fails with the error I show in the description.
But if I get rid of the SCP that enforces the bucket encryption then it works fine.
