### ISSUE TITLE
Cannot read property 'DevelopmentAccount' of undefined

### ISSUE THREAD

**Issue by studiowebux** [org-formation/org-formation-cli#376]
### Subject of the issue
Trying to use the templating engine to populate the DNS.

We have two accounts,
- non-prod : plan to host these stages : dev,qa,test
- prod : and for prod: staging (and the root hosted zone is used directly for the production)

we want to automate the way to populate the hosted zone.

The idea is to loop through each subdomain and create a cloudformation stack in the proper account and then create the root hosted zone in the production account.

I've look into the dns exemple, but because of the subdomain array I wasn't able to reach our goal.
then i've follow this : https://github.com/org-formation/org-formation-cli/tree/bbdef267930b6b50eb0fa32bc491b084afccbe09/test/integration-tests/resources/scenario-text-template-mixed and it was better but I have the issue below (with maybe a fix, I'm not sure).

### Your environment
* version of org-foramtion (ofn --version) **0.9.20-beta.3**
* version of node (node --version) **v14.18.1**
* which OS/distro **MacOS 11.6.4**

### Steps to reproduce

```dns.yml
OrganizationUpdate:
  Type: update-organization
  Template: ./organization.yml

OrganizationBindings:
  DevelopmentAccount:
    Account:
      - !Ref DevelopmentAccount
  ProductionAccount:
    Account:
      - !Ref ProductionAccount

# Populate the development account to start with
IncludeHostedZone:
  Type: include
  Path: ./templates/hosted-zone.njk
  TemplatingContext:
    Subdomains: "dev,qa,test"
    HostedZoneBinding: Fn::EnumTargetAccounts DevelopmentAccount
    RootHostedZoneBinding: Fn::EnumTargetAccounts ProductionAccount
```

hosted-zone.njk
```yml
{% for sub in Subdomains.split(",") %}
hostedZone{{ sub | capitalize  }}:
  Type: update-stacks
  StackName: subdomain-{{ sub }}
  Template: ./route53.yml
  MaxConcurrentStacks: 10
  Parameters:
    Subdomain: {{ sub }}
    RootHostedZoneName: !GetAtt CurrentAccount.Tags.Domain
  OrganizationBindings:
    HostedZoneBinding:
      Account: 
{% for acc in HostedZoneBinding %}
        - !Ref {{ acc.LogicalId }}
{% endfor %}
    RootHostedZoneBinding:
      Account: 
{% for acc in RootHostedZoneBinding %}
        - !Ref {{ acc.LogicalId }}
{% endfor %}
{% endfor %}  
```

route53.yml
```yml
AWSTemplateFormatVersion: '2010-09-09-OC'

# Include file that contains Organization Section.
# The Organization Section describes Accounts, Organizational Units, etc.
Organization: !Include ../organization.yml

# Any Binding that does not explicitly specify a region will default to this.
# Value can be either string or list
DefaultOrganizationBindingRegion: ca-central-1


# Section contains a named set of Bindings.
# Bindings determine what resources are deployed where
# These bindings can be !Ref'd from the Resources in the resource section
OrganizationBindings:

  # binding for HostedZone, HostedZoneIdParam, HostedZoneNameParam
  # Targets accounts
  HostedZoneBinding:
    # AccountsWithTag: subdomain

  # binding for RootHostedZone, ParentNsRecord
  # Root NS ACCOUNT
  RootHostedZoneBinding:
    # IncludeMasterAccount: false

Parameters:
  Subdomain:
    Type: String

  RootHostedZoneName:
    Type: String

Resources:

  #=========================================#
  # Zone
  #=========================================#

  HostedZone:
    Type: AWS::Route53::HostedZone
    OrganizationBinding: !Ref HostedZoneBinding
    Properties:
      HostedZoneConfig:
        Comment: Domain Hosted Zone
      Name: !Sub '${Subdomain}.${RootHostedZoneName}.'

  HostedZoneIdParam:
    Type: AWS::SSM::Parameter
    OrganizationBinding: !Ref HostedZoneBinding
    Properties:
      Name: !Sub '/${AWSAccount.Tags.Prefix}/domains/hosted_zone_id'
      Type: String
      Value: !GetAtt AWSAccount.Resources.HostedZone

  HostedZoneNameParam:
    Type: AWS::SSM::Parameter
    OrganizationBinding: !Ref HostedZoneBinding
    Properties:
      Name: !Sub '/${AWSAccount.Tags.Prefix}/domains/hosted_zone_name'
      Type: String
      Value: !Sub '${Subdomain}.${RootHostedZoneName}.'

  # #=========================================#
  # # Parent Record
  # #=========================================#

  RootHostedZone:
    Type: AWS::Route53::HostedZone
    OrganizationBinding: !Ref RootHostedZoneBinding
    Properties:
      HostedZoneConfig:
        Comment: Root domain
      Name: !Ref RootHostedZoneName

  # # be aware that changing the logicalName for a AWS::Route53::RecordSet resource
  # # might result in an error. workaround is to remove the resource and then add it.
  # ParentNsRecord:
  #   DependsOn: RootHostedZone
  #   Type: AWS::Route53::RecordSet
  #   OrganizationBinding: !Ref RootHostedZoneBinding
  #   ForeachAccount: !Ref HostedZoneBinding
  #   Properties:
  #     Type: NS
  #     HostedZoneName: !Sub '${RootHostedZoneName}.'
  #     Name: !Sub '${CurrentAccount.Tags.subdomain}.${RootHostedZoneName}.'
  #     TTL: 86400
  #     ResourceRecords: !GetAtt CurrentAccount.Resources.HostedZone.NameServers

```

### Expected behaviour
Able to deploy each subdomain in the development/production account based on the mappings passed from dns.yml.
I successfully deployed `subdomain-dev` but I had to edit the `build-configuration.js` file with the following addition: 

<img width="898" alt="image" src="https://user-images.githubusercontent.com/37277136/170608047-d3e9b1db-c471-4641-8790-a6352f9ffd95.png">

### Actual behaviour
> I've added console.debug in `.nvm/versions/node/v14.18.1/lib/node_modules/aws-organization-formation/dist/src/build-tasks/build-configuration.js:125:21`
```bash
org-formation perform-tasks dns.yml --profile some-profile --verbose --print-stack
dns.yml
{
  OrganizationUpdate: { Type: 'update-organization', Template: './organization.yml' },
  OrganizationBindings: {
    DevelopmentAccount: { Account: [Array] },
    ProductionAccount: { Account: [Array] }
  },
  IncludeHostedZone: {
    Type: 'include',
    Path: './templates/hosted-zone.njk',
    TemplatingContext: {
      Subdomains: 'dev,qa,test',
      HostedZoneBinding: 'Fn::EnumTargetAccounts DevelopmentAccount',
      RootHostedZoneBinding: 'Fn::EnumTargetAccounts ProductionAccount'
    }
  }
}
{
  DevelopmentAccount: { Account: [ [Object] ] },
  ProductionAccount: { Account: [ [Object] ] }
}
DevelopmentAccount { Account: [ { Ref: 'DevelopmentAccount' } ] }
undefined
ERROR: unexpected error occurred...
Cannot read property 'DevelopmentAccount' of undefined
TypeError: Cannot read property 'DevelopmentAccount' of undefined
    at BuildConfiguration.enumBuildConfigurationFromBuildFile (/Users/t/.nvm/versions/node/v14.18.1/lib/node_modules/aws-organization-formation/dist/src/build-tasks/build-configuration.js:192:42)
    at BuildConfiguration.enumBuildConfiguration (/Users/t/.nvm/versions/node/v14.18.1/lib/node_modules/aws-organization-formation/dist/src/build-tasks/build-configuration.js:125:21)
    at new BuildConfiguration (/Users/t/.nvm/versions/node/v14.18.1/lib/node_modules/aws-organization-formation/dist/src/build-tasks/build-configuration.js:25:27)
    at PerformTasksCommand.performCommand (/Users/t/.nvm/versions/node/v14.18.1/lib/node_modules/aws-organization-formation/dist/src/commands/perform-tasks.js:49:24)
    at PerformTasksCommand.invoke (/Users/t/.nvm/versions/node/v14.18.1/lib/node_modules/aws-organization-formation/dist/src/commands/base-command.js:115:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

```

Let me know if it was expected and if I did something wrong to get that result, or if you have a better way to proceed to achieve that type of actions.

Thank you 😊

**Comment by studiowebux** [comment]
FYI, I've reworked the whole thing and reinstall the package, and so far so good, I guess I did something wrong.


By removing :

```yml
...

HostedZoneBinding: Fn::EnumTargetAccounts DevelopmentAccount
RootHostedZoneBinding: Fn::EnumTargetAccounts ProductionAccount
```

it seems to avoid the issue mentioned above.
