### ISSUE TITLE
Your account is not a member of an organization.

### ISSUE THREAD

**Issue by samuelcastro** [org-formation/org-formation-cli#380]
### Subject of the issue
Getting an error when attempting to update org-formation: `Your account is not a member of an organization.`

### Your environment
* version of org-foramtion (ofn --version): 0.9.20-beta.3
* version of node (node --version): v14.17.0
* which OS/distro: macOS Monterey

### Steps to reproduce
The `init` command worked just fine, the problem arises after attempting to add new account in the `org-formation.yml` file and update it using `org-formation update organization.yml`

```yml
AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 9999999999

Organization:
  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: mybook.space
      AccountId: '9999999999'
      RootEmail: samuel@mycompany.com
      Alias: mycompany

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole

  ProductionOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: production
      Accounts: !Ref ProductionAccount

  DevelopmentOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: development
      Accounts:
        - !Ref DevelopmentAccount

  ProductionAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Production Account
      RootEmail: samuel+prod@mycompany.com

  DevelopmentAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Development Account
      RootEmail: samuel+dev@mycompany.com
```

### Expected behaviour
Be able to create more accounts

### Actual behaviour
```
ERROR: unable to list accounts
Your account is not a member of an organization.
AWSOrganizationsNotInUseException: Your account is not a member of an organization.
```
