### ISSUE TITLE
Feature request: an org-formation conditional function

### ISSUE THREAD

**Issue by zaro0508** [org-formation/org-formation-cli#381]
### Subject of the issue
Org-formation has [functions](https://github.com/org-formation/org-formation-cli/blob/master/docs/task-files.md#functions).  I would like a conditional function, an `!If` function...

Example:
```
Cloudtrail:
  Type: update-stacks
  StackName: 'cloudtrail'
  ..
  ..
  DefaultOrganizationBinding:
    Account: '*'
  Parameters:
    EncryptTrail: !If [!Ref LogCentralAccount, !Ref CurrentAccount, "true", "false"]
```

Expected result:
Deploy this cloudtrail stack to all accounts.  When this stack is deployed to the LogCentralAccount account pass in "true" for EncryptTrail, otherwise pass in "false"
