### ISSUE TITLE
init-pipelines - attach SCP to OrganizationRoot (Missing required key 'TargetId' in param)

### ISSUE THREAD

**Issue by wwojcik** [org-formation/org-formation-cli#385]
### problem with codebuild during attach SCP to organization root

Stack generated by command 
```
org-formation  init-pipeline --region eu-west-1
```

Error

```
[Container] 2022/06/22 07:33:57 Running command org-formation perform-tasks ./organization-tasks.yml --no-color --state-bucket-name organization-formation-xxxx --state-object state.json --print-stack
--
40 | INFO: Executing: include 000-organization-build/organization-tasks.yml.
41 | INFO: Executing: update-organization organization.yml.
42 | ERROR: failed executing task: Attach Policy (DenyChangeOfOrgRoleSCP) OC::ORG::OrganizationRoot OrganizationRoot MissingRequiredParameter: Missing required key 'TargetId' in params
43 | ERROR: Task OrganizationUpdate execute failed. reason: Missing required key 'TargetId' in params
44 | Missing required key 'TargetId' in params
45 | MissingRequiredParameter: Missing required key 'TargetId' in params
46 | at ParamValidator.fail (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/param_validator.js:50:37)
47 | at ParamValidator.validateStructure (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/param_validator.js:62:14)
48 | at ParamValidator.validateMember (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/param_validator.js:89:21)
49 | at ParamValidator.validate (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/param_validator.js:34:10)
50 | at Request.VALIDATE_PARAMETERS (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/event_listeners.js:132:42)
51 | at Request.callListeners (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
52 | at callNextListener (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
53 | at /usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/event_listeners.js:86:9
54 | at finish (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/config.js:396:7)
55 | at /usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/config.js:414:9
56 | at RemoteCredentials.get (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/credentials.js:127:7)
57 | at getAsyncCredentials (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/config.js:408:24)
58 | at Config.getCredentials (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/config.js:428:9)
59 | at Request.VALIDATE_CREDENTIALS (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/event_listeners.js:81:26)
60 | at Request.callListeners (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
61 | at Request.emit (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
```

### Your environment
* version of org-formation: 1.0.0

### Steps to reproduce
organization.yml
```
# OU
  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole
      ServiceControlPolicies:
        - !Ref DenyChangeOfOrgRoleSCP
# SCP
  DenyChangeOfOrgRoleSCP:
      Type: OC::ORG::ServiceControlPolicy
      Properties:
        PolicyName: DenyChangeOfOrgRole
        Description: Deny changing the IAM role used for organization access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: DenyChangeOfOrgRole
              Effect: Deny
              Action:
                - 'iam:Attach*'
                - 'iam:Create*'
                - 'iam:Delete*'
                - 'iam:Detach*'
                - 'iam:PutRole*'
                - 'iam:Update*'
              Resource:
                - 'arn:aws:iam::*:role/OrganizationAccountAccessRole'
 ```
