### ISSUE TITLE
Perform-task : update organization output hides newly created account Id

### ISSUE THREAD

**Issue by iamjaekim** [org-formation/org-formation-cli#395]
### Subject of the issue
After running perform-task for organization update, the output isn't showing account Id. (Line 61)
<img width="916" alt="image" src="https://user-images.githubusercontent.com/46606360/177803333-71df2635-d844-4ea4-a643-1c37ceb0634d.png">

### Your environment
* version of org-foramtion (ofn --version) v1.0.2
* version of node (node --version) node 14
* which OS/distro Mac 12.4

### Steps to reproduce

tasks.yaml
```yaml
OrganizationUpdate:
  Type: update-organization
  Template: ./organization.yml
  skip: false

```

organization.yaml
```yaml

...all root stuff here

# GREENFIELD TEST OU and ACCTs
  OrgFormationTestOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: OrgFormation-TestOU
      Accounts:
        - !Ref OrgFormationTestAccount

  OrgFormationTestAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: OrgFormation Test Account
      RootEmail: admin+orgformationtestaccount@extend.com
```

and run ` org-formation perform-tasks tasks.yaml` to create new account. And check the output. 

### Expected behaviour
Line 61, should show newly create account id and whatever detail it used to show.

### Actual behaviour
Line 61 shows Create ([Object, Object])
