### ISSUE TITLE
Convert Fn::EnumTargetAccounts list into a string of values

### ISSUE THREAD

**Issue by zaro0508** [org-formation/org-formation-cli#412]
### Subject of the issue
I’m trying to setup multi-account patching using the AWS Systems Manager by following this [aws doc](https://aws.amazon.com/blogs/mt/scheduling-centralized-multi-account-multi-region-patching-aws-systems-manager-automation/) that references a [Scheduled-Patch-Automation template](https://github.com/aws-samples/aws-systems-manager-schedule-central-patch-example/blob/main/Templates/Scheduled-Patch-Automation.yaml).  That template passing in a TargetAccounts parameter environment variable as a string of values (i.e.  “1111, 2222, 3333” ) because environment variables can only accept a string.  I tried using Fn::EnumTargetAccounts to pass in all my org accounts in my custom PatchMemberBinding like so..

in task.yaml :
```
PatchManager:
  Type: update-stacks
  DependsOn: PatchResourceGroup
  Template: Scheduled-Patch-Automation.yaml
  StackName: patchmanager
  DefaultOrganizationBindingRegion: !Ref primaryRegion
  DefaultOrganizationBinding:
    Account: !Ref accountId
  OrganizationBindings:
    PatchMemberBinding:
      Account: '*'
      IncludeMasterAccount: true
  Parameters:
    EventBridgeRuleSchedule: "cron(15 22 ? * TUE *)"
    ResourceGroupName: !CopyValue sagebase-systemsmanager-patch-resource-group-TagBasedGroupName
    RunPatchBaselineOperation: "Scan"
    TargetRegionIds: "us-east-1"
```

in Scheduled-Patch-Automation.yaml :
```
  MultiAccountPatchingBlogLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
          TargetAccounts: !Join [",", Fn::EnumTargetAccounts PatchMemberBinding '${account}']
```

However this does not work because Fn::EnumTargetAccounts provides a list of strings (i.e. ["1111", "2222", "3333"] not a string of values (i.e.  “1111, 2222, 3333”).   Wondering if anybody can help me figure out a workaround for this problem?

### Environment
* org-foramtion 1.0.3
* Node v16.13.2
* MAC OSX Monterey 12.3.1

**Comment by zaro0508** [comment]
The expression `Fn::EnumTargetAccounts PatchMemberBinding '${account}` does work and does produce a list of AWS account IDs.  I have attempted various combinations to join the list together (i.e. `TargetAccounts: !Join [",", Fn::EnumTargetAccounts PatchMemberBinding '${account}']`) however nothing I have tried seems to work.

using this
```
           TargetAccounts: !Join
                - ","
                - Fn::EnumTargetAccounts PatchMemberBinding '${account}'
```

resulted in
```
DEBG: Stack sagebase-systemsmanager-patchmanager in account XXXXXXXX9929 (us-east-1) update starting... (XXXXXXXX9929 = SecurityCentralAccount)
ERROR: error updating CloudFormation stack sagebase-systemsmanager-patchmanager in account XXXXXXXX9929 (us-east-1).
Template error: every Fn::Join object requires two parameters, (1) a string delimiter and (2) a list of strings to be joined or a function that returns a list of strings (such as Fn::GetAZs) to be joined. (XXXXXXXX9929 = SecurityCentralAccount)
ERROR: Stack sagebase-systemsmanager-patchmanager in account XXXXXXXX9929 (us-east-1) update failed. reason: Template error: every Fn::Join object requires two parameters, (1) a string delimiter and (2) a list of strings to be joined or a function that returns a list of strings (such as Fn::GetAZs) to be joined. (XXXXXXXX9929 = SecurityCentralAccount)
Template error: every Fn::Join object requires two parameters, (1) a string delimiter and (2) a list of strings to be joined or a function that returns a list of strings (such as Fn::GetAZs) to be joined.
ValidationError: Template error: every Fn::Join object requires two parameters, (1) a string delimiter and (2) a list of strings to be joined or a function that returns a list of strings (such as Fn::GetAZs) to be joined.
    at Request.extractError (/Users/zaro0508/work-sage/organizations-infra/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/zaro0508/work-sage/organizations-infra/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/zaro0508/work-sage/organizations-infra/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/zaro0508/work-sage/organizations-infra/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/Users/zaro0508/work-sage/organizations-infra/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/zaro0508/work-sage/organizations-infra/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/zaro0508/work-sage/organizations-infra/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/zaro0508/work-sage/organizations-infra/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/zaro0508/work-sage/organizations-infra/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/Users/zaro0508/work-sage/organizations-infra/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/Users/zaro0508/work-sage/organizations-infra/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/zaro0508/work-sage/organizations-infra/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/Users/zaro0508/work-sage/organizations-infra/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/zaro0508/work-sage/organizations-infra/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/zaro0508/work-sage/organizations-infra/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/zaro0508/work-sage/organizations-infra/node_modules/aws-sdk/lib/request.js:38:9)
```

using this
```
            TargetAccounts: !Join
                - ","
                - [Fn::EnumTargetAccounts PatchMemberBinding '${account}']
```

resulted in
```
INFO: Executing: update-stacks org-formation/090-systems-manager/Scheduled-Patch-Automation.yaml sagebase-systemsmanager-patchmanager.
ERROR: Task PatchManager execute failed. reason: unable to load file org-formation/090-systems-manager/Scheduled-Patch-Automation.yaml.
reason: missed comma between flow collection entries (237:64)

 234 |  ...  TargetAccounts
 235 |  ...
 236 |  ...
 237 |  ... Accounts PatchMemberBinding '${account}']
------------------------------------------^
 238 |  ...  TargetRegionIds
 239 |  ... tion: !Ref RunPatchBaselineOperation.
```

**Comment by brcourt** [comment]
```
MultiAccountPatchingBlogLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
          TargetAccounts: 
            Fn::Join:
              - ","
              - - Fn::EnumTargetAccounts PatchMemberBinding ${account}
```
Using the long form for the intrinsic function, and passing the Fn::EnumTargetAccounts as a nested list should work. When I print a sample, I get the following output:

```
MultiAccountPatchingBlogLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
          TargetAccounts:
            Fn::Join:
              - ','
              - - '111111111111'
                - '222222222222'
                - '333333333333'
```
Which looks correct to me, since Join has a list argument of two items, the first item being the delimiter, the second being an array of values.
