### ISSUE TITLE
Account Tags with value of false is applied as empty

### ISSUE THREAD

**Issue by castaples** [org-formation/org-formation-cli#453]
### Subject of the issue
The following false value for a TagA get applied as `(empty value)` when viewed in the Console, while TagB value of true is correctly applied.

```yaml
  TestAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Testing123
      AccountId: '12345678910'
      RootEmail: test@madeup.com
      Tags:
        TagA: false
        TagB: true
```

This can be corrected by quoting the value as `'false'` but still feels like a bug, as true is correctly applied.

### Your environment
* version of org-formation: 1.0.6
* version of node: 8.19.2
* which OS/distro: ubuntu-latest (GitHub actions)

### Steps to reproduce
Set an Account Tag value to false (with no quotes)

### Expected behaviour
The Account would be tagged with the string 'false', as it is for true values.

### Actual behaviour
The Account Tag has an empty value
