### ISSUE TITLE
ZipBeforePut missing from docs

### ISSUE THREAD

**Issue by yannickvr** [org-formation/org-formation-cli#458]
### Subject of the issue
The CopyToS3 task has an optional parameter `ZipBeforePut` which is only mentioned in the release notes and in an example, not in the general docs.

### Your environment
* version of org-formation: latest

### Steps to reproduce
```
DeployLambdaSourceCode:
  Type: copy-to-s3
  RemotePath: !Sub
  - s3://${bucket}/lambdas/my-lambda-source-${hashOfDir}.zip
  - { bucket: !Ref deploymentBucketName, hashOfDir: !MD5Dir ./src }
  LocalPath: ./src
  ZipBeforePut: true
  OrganizationBinding:
    IncludeMasterAccount: true
    Region: eu-central-1
```

I will open a PR soon.
