### ISSUE TITLE
Feature request: !StringJson function

### ISSUE THREAD

**Issue by zaro0508** [org-formation/org-formation-cli#473]
### Subject
I would like a function that's the opposite of [!JsonString](https://github.com/org-formation/org-formation-cli/blob/master/docs/task-files.md#jsonstring) to support my use cases.  The general use case is to convert a string to a json object then pass it to a TemplatingContext parameter.

### Use cases
These use cases are derived from the [Templating context example in the docs](https://github.com/org-formation/org-formation-cli/blob/master/docs/task-files.md#templating):

Read ports in from a file, convert the string to a json list object and then pass it to the ports parameter:
```
SecurityGroupExample:
  Type: update-stacks
  Template: ./security-group.njk
  StackName: SecurityGroupExample
  Parameter:
    ports: !StringJson 
      - !Readfile "ports.json"
 ```

Get data from a REST API endpoint, convert the string to a json dictionary object and then pass it to the hounds TemplatingContext parameter:
```
DogsExample:
  Type: update-stacks
  Template: ./dogs.njk
  StackName: DogsExample
  TemplatingContext:
    hounds: !StringJson 
      - !Cmd "wget -qO-  https://dog.ceo/api/breed/hound/list"
 ```

**Comment by OlafConijn** [comment]
have you tried:
```
SecurityGroupExample:
  Type: update-stacks
  Template: ./security-group.njk
  StackName: SecurityGroupExample
  Parameter:
    ports: !Include "ports.json"
```

I dont think this will help with the `!Cmd "wget -qO-  https://dog.ceo/api/breed/hound/list"` though....

**Comment by zaro0508** [comment]
I have not tried `!Include` in that context @OlafConijn.  I will investigate that.

> I dont think this will help with the !Cmd "wget -qO-  https://dog.ceo/api/breed/hound/list" though....

If `!Cmd` doesn't work then how about a new org-formation `!Request` function would basically do a  "curl -X GET https://dog.ceo/api/breed/hound/list"?  This is how it would work..

Get data from a REST API endpoint, convert the string to a json dictionary object and then pass it to the hounds TemplatingContext parameter:

```
DogsExample:
  Type: update-stacks
  Template: ./dogs.njk
  StackName: DogsExample
  TemplatingContext:
    hounds: !StringJson 
      - !Request "https://dog.ceo/api/breed/hound/list"
```
