### ISSUE TITLE
feat: annotate-organization (aka Control Tower support)

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/org-formation-cli#483]
### Context

Most org-formation users use org-formation as both "account factory" and "cross-account resource provisioning".
Org-formation can do both, but using org-formation together with another tool (e.g. Control Tower) as account factory is currently not possible. The reason this is not possible is that the perform-tasks commands (used for cross-account resource provisioning), relies on the organization.yml file to evaluate the organization bindings (= to figure out what templates needs to be deployed where).

Using the organization.yml as a map to navigate the AWS organization aligns well with org-formation playing the role of "account factory". It aligns well with having a different tool (e.g. Control Tower) be the account-factory.

### Proposed design

currently, when running perform-tasks it is required to have an `update-organization` task within the task files. This task is used to locate the organization.yml file.

Allowing a similar task `annotate-organization` to be used (instead of `update-organization`) would allow perform-tasks to read the organization structure (OUs/Account/SCPs) to read from the AWS Organizations service.

``` yaml
AnnotateOrganization:
  Type: annotate-organization
  # default role for cross account access 
  DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole 
  # account mappings allow account Ids to be mapped to Logical Names. This allows for re-usable templates to use 
  # logical names and to be deployed to different organizations without having to modify the templates.
  AccountMapping:
    SecurityAccount: 123123123123
    LogArchiveAccount: 123123123124 
```
