### ISSUE TITLE
Feature request: a function to get data from a rest API

### ISSUE THREAD

**Issue by zaro0508** [org-formation/org-formation-cli#486]
I would like to have an generic org-formation function that I could use to make a request to any REST API and pass the response data into either a cloudformation or a TemplatingContext parameter.

Example of get data from a REST API endpoint then pass it into a `hounds` parameter:
```
DogsExample:
  Type: update-stacks
  Template: dogs.yaml
  StackName: DogsExample
  Parameters:
    cfn-hounds:  !Request "https://dog.ceo/api/breed/hound/list"
  TemplatingContext:
    tc-hounds:  !Request "https://dog.ceo/api/breed/hound/list"
```
