### ISSUE TITLE
!GetAtt not working in Tags on update-stack task

### ISSUE THREAD

**Issue by mgorski-mg** [org-formation/org-formation-cli#491]
### Subject of the issue
I'm trying to copy the tag from CurrentAccunt to the stack level tag.

organization.yml:
```
ExampleAccount:
  Type: OC::ORG::Account
  Properties:
    AccountName: Sample
    RootEmail: sample@sample.com
    Tags:
      environment: prod
```

tasks.yml:
```
Parameters:
  EnvParam:
    Type: String

Examplestack:
  Type: update-stacks
  Template: ./sample.yml
  StackName: sample
  DefaultOrganizationBindingRegion: us-east-1
    DefaultOrganizationBinding:
    Account:
      - !Ref ExampleAccount
      - !Ref ExampleAccount2
      - !Ref ExampleAccount3
  Parameters:
    environment: !GetAtt CurrentAccount.Tags.environment
  Tags:
    environment: !GetAtt CurrentAccount.Tags.environment
    environment2: !Ref EnvParam
```

Instead of performing `!GetAtt` function, it converts value into JS object.
It works properly for Parameters.
For Tags it seems to work only with Parameters and `!Ref` function.

### Your environment
* version of org-foramtion: 1.0.9
* version of node: 18.15.0
* which OS/distro: Windows 11

### Steps to reproduce
Just add Tag like mentioned to update-stack task.

### Expected behaviour
Function `!GetAtt` should be performed and the tag `environment` should be reused from `CurrentAccount`.

### Actual behaviour
` !GetAtt CurrentAccount.Tags.environment` is changed to JS object.
