### ISSUE TITLE
Enable additional regions on account creation

### ISSUE THREAD

**Issue by diegoroccia** [org-formation/org-formation-cli#581]
### Subject of the issue

Please excuse if the feature is documented and I could just not finf it.

I am looking into how to enable additional regions on account creation. It has to be on account creation because I am setting AWS SSO in that region, so not having the region enabled makes the pipeline fail because the org-formation is unable to assume the role in the target account

Specifically, I am using ap-east-1

### Your environment
* version of org-foramtion (ofn --version)
* version of node (node --version)
* which OS/distro

### Steps to reproduce
Tell us how to reproduce this issue. Please provide ofn projct files if possible,
you can use [this template](https://plnkr.co/edit/m568SDw2KPufQsUl?p=preview) as a base.
https://plnkr.co/edit/m568SDw2KPufQsUl

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by yannickvr** [comment]
I'm assuming something among the lines of this?

```
  ProductionAccount:
    Type: OC::ORG::Account
    Properties:
      RootEmail: production@myorg.com
      AccountName: Production Account
      Tags:
        budget-alarm-threshold: '2500'
        account-owner-email: my@email.com
      OptInRegions:
        - af-south-2
        - ap-east-1
```
