### ISSUE TITLE
Template context within tasks configuration and organization update produce incosistent state

### ISSUE THREAD

**Issue by project0** [org-formation/org-formation-cli#600]
### Subject of the issue

Update-organization is produces and uses different states when template context is used. It looks like only the template context given the CLI is fully respected. Strangely the organization is updates as expected with all template settings, but the stored state  in s3 is wrong and later also not used for other operations. 
Additionally nunjuck debug output template produces the correct yaml file, but as i said before not used in later operations. 

### Your environment
* version of org-foramtion (ofn --version): 1.0.16
* version of node (node --version)
* which OS/distro

### Steps to reproduce

assume you set the follwoing template context set via CLI
```json
{
  "context": {
    "id": "flowers-test"
    }
}
```

and enrich the template context with additional variables in the tasks
```yaml
OrganizationUpdate:
  Type: update-organization
  Template: ./organization.yaml
  TemplatingContext:
    context: {{ context | dump | safe }}
    email-domain: "test.com"
```

### Expected behaviour

TemplatingContext should be respected the same way as with tasks. The stored state should also reflect it and the dependend tasks should be able to read the (final) produced state as given with the template context.

### Actual behaviour
TemplatingContext given in the tasks.yaml is partially ignored, the org is updated as given, but the state is produced differently.
