### ISSUE TITLE
update-cdk fails when setting MaxConcurrentTasks to a value higher than 1

### ISSUE THREAD

**Issue by DannyBlazejczak** [org-formation/org-formation-cli#602]
This is the task configuration:
```yaml
AccountQuotasNetworkAllRegions:
  Type: update-cdk
  Path: ../../../../../modules/aws-quotas-cdk
  RunNpmInstall: true
  RunNpmBuild: true
  Parameters:
    resource_prefix: !Ref resourcePrefix
    permissions_boundary: !Ref permissionBoundaryName
    vpc_maximum_number_of_vpcs_per_region: <%= it.ServiceQuotaOptions.VpcMaximumNumberOfVPCsPerRegion %> # default is 5
    ec2_maximum_number_of_elastic_ips:  <%= it.ServiceQuotaOptions.Ec2MaximumNumberOfElasticIPs %> # default is 5
    route53_maximum_number_of_resolver_endpoints: <%= it.ServiceQuotaOptions.Route53MaximumNumberOfResolverEndpoints %> # default is 4
    vpc_interface_vpc_endpoints: <%= it.ServiceQuotaOptions.VpcInterfaceVPCEndpoints %> # default is 50
    vpc_gateway_vpc_endpoints: <%= it.ServiceQuotaOptions.VpcGatewayVPCEndpoints %> # default is 20
  # MaxConcurrentTasks: 10 # There is a bug in org-formation that appends 
  OrganizationBinding:
```

When I set the `MaxConcurrentTasks: 10`, then the resulting CLI is generated as follows:

```sh
  npx cdk deploy --all --require-approval=never  -c 'resource_prefix=aefb-79ef6' -c 'permissions_boundary=' -c 'vpc_maximum_number_of_vpcs_per_region=5' -c 'ec2_maximum_number_of_elastic_ips=5' -c 'route53_maximum_number_of_resolver_endpoints=12' -c 'vpc_interface_vpc_endpoints=50' -c 'vpc_gateway_vpc_endpoints=20'--output cdk.out/767828743315 in account 767828743315 (767828743315 = G1PerSquadNetworkAccount)
```

The problem is that there is no space before the `--output` and the command fails, and comes from this code here:

https://github.com/org-formation/org-formation-cli/blob/42b7339db1e8bae567591b936b4d1a67dfd8bb54/src/plugin/impl/cdk-build-task-plugin.ts#L139
