### ISSUE TITLE
Allow Join with CopyValue in tasks file

### ISSUE THREAD

**Issue by eduardomourar** [org-formation/org-formation-cli#79]
Take the following snippet that exports a value using the default property of a resource using the `!Ref` intrinsic function:

```yaml
AWSTemplateFormatVersion: 2010-09-09

Resources:

  ElasticIpNatGateway:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

Outputs:

  NatGatewayIp:
    Description: The NAT Gateway public IP
    Value: !Ref ElasticIpNatGateway
    Export:
      Name: 'exported-ngw-ip'
```

Whenever trying to use `!Join [ '', [ !CopyValue 'exported-ngw-ip', '/32' ] ]`, the following is being passed as string to CloudFormation: `[object Object]`

We can use the `!ImportValue` as a workaround if the stack is located in the same account and region.
